package org.tae.exercises.people;

public enum LastNames {
    GOMEZ, CELIS, MOGOLLON, PABON, VARGAS, MEDINA, BOHORQUEZ, ORTIZ, MORENO, BEJARANO, CASTAÑEDA, OBANDO, OTALORA, ARCINIEGAS,
    MARIN, LIZARAZO, GONZALEZ, SUCRE, JIMENEZ, ROMERO, MARQEZ, CASTRO, CAMACHO, LOZANO, CASTILLO, MONTES
}
