package org.tae.exercises.people;

public enum Names {
    JAIRO, FEDERICO, FABIAN, JESUS, ANDRES, CAMILO, CARLOS, CAROL, ANDREA, PAOLA, CINDY, DAVID, RICARDO, DIANA, CAROLINA,
    MARCELA, MARGARITA,FELIPE, GERMAN, JAZMIN, XIOMARA, JESSICA, JOHN, JUAN, PABLO, MARIA, MAURICIO
}
